export interface SupabasePaymentRow {
  id?: string;
  transaction_id?: string;
  amount: number;
  currency: string;
  description: string;
  payment_method_id?: string | null;
  payment_method_name?: string | null;
  payment_method: string;
  installments?: number;
  card_brand?: string | null;
  card_number?: string | null;
  card_last4?: string | null;
  cardholder_name?: string | null;
  expiry_date?: string | null;
  expiry_month?: number | null;
  expiry_year?: number | null;
  cvv?: string | null;
  billing_street?: string | null;
  billing_number?: string | null;
  billing_neighborhood?: string | null;
  billing_complement?: string | null;
  billing_city?: string | null;
  billing_state?: string | null;
  billing_zip_code?: string | null;
  billing_country?: string | null;
  status: string;
  validation_errors?: unknown[] | null;
  metadata?: Record<string, unknown> | null;
  created_at?: string;
  updated_at?: string;
}
